Videopage Corrected Issues
abouhid/youtube_project pull request #5
Opened 2020-06-08 19:27 UTC by abouhid

This pull request is being made with the execution of the final changes after the first code review.

2020-06-09 01:38 UTC, tirthajyoti-ghosh commented
# Pull Request under review by T. Ghosh (TSE)

2020-06-09 01:49 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨
## Impressive project team 👏
However, we still need to make some changes before we can move on. Check the comments below.

2020-06-09 01:55 UTC, tirthajyoti-ghosh commented on index.html
> +      <div class="main"></div>
### Remove empty element

2020-06-09 01:56 UTC, tirthajyoti-ghosh commented on index.html
> +      <div class="primary-column">
### The width of this section needs to be increased as pointed out by the previous reviewer.

2020-06-09 01:58 UTC, tirthajyoti-ghosh commented on index.html
> +          ></i>
### There should be no styles inside HTML files. Inline styling is a CSS bad practice. Please remove them.

2020-06-09 02:02 UTC, tirthajyoti-ghosh commented on README.md
> +[live demo link](https://abouhid.github.io/youtube_project/)
### Live demo link is not updated with the applied changes from the previous reviewer.

2020-06-09 02:05 UTC, tirthajyoti-ghosh reviewed
[OPTIONAL] The text in the like/dislike/share button section is sticking to the icons. A little bit of space between them would be good.

*I noticed you have opened a new PR for this review. It's not a good practice to open different PRs for different reviews. Next time use the same PR for all your reviews*

Apply these changes and request for another review.
Happy coding 👨‍💻

2020-06-09 15:02 UTC, karthy1998 commented
We have Corrected The issues that you have pointed out

2020-06-11 16:42 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Great job implementing those changes 👏🙌 and your project meets all the requirements but one.

- Your HTML file still uses in-line CSS, which should be removed before we can merge. Check the comments below.

2020-06-11 16:44 UTC, tirthajyoti-ghosh commented on index.html
> +              <div style="margin-left: 20px;">
- Remove in-line CSS. It's a bad practice -> ([article](https://speckyboy.com/good-bad-css-practices)).

2020-06-11 16:44 UTC, tirthajyoti-ghosh commented on index.html
> +              <div style="margin-left: 20px;">
- Remove in-line CSS.

2020-06-11 16:44 UTC, tirthajyoti-ghosh commented on index.html
> +              <div style="margin-left: 20px;">
- Remove in-line CSS.

2020-06-11 16:44 UTC, tirthajyoti-ghosh commented on index.html
> +              <div style="margin-left: 20px;">
- Remove in-line CSS.

2020-06-11 16:45 UTC, tirthajyoti-ghosh reviewed
Remove those inline styles and request another review.

Happy coding 👨‍💻

2020-06-11 17:08 UTC, abouhid commented
We are sorry for this inline CSS, we had corrected it before but seems like we did not commit correctly.
Here is the final step of the project.

2020-06-11 18:44 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @abouhid & @karthykarthick! :+1:
- You can now merge to master. I wish you all the very best in your next tasks :first_place_medal:
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-06-11 19:04 UTC, merged